import type { KnowledgeType, RelationType } from "@/types";

/** Ordered list of the ten knowledge node types (single source of truth). */
export const KNOWLEDGE_TYPES: KnowledgeType[] = [
  "project",
  "agent",
  "research",
  "paper",
  "dataset",
  "experiment",
  "report",
  "note",
  "session",
  "activity",
];

/** English singular labels (fallback; overridden per-language via i18n). */
export const TYPE_LABEL: Record<KnowledgeType, string> = {
  project: "Project",
  agent: "Agent",
  research: "Research Project",
  paper: "Paper",
  dataset: "Dataset",
  experiment: "Experiment",
  report: "Report",
  note: "Note",
  session: "Session",
  activity: "Activity",
};

/** English relation phrases (fallback; overridden via i18n). */
export const RELATION_LABEL: Record<RelationType, string> = {
  belongs_to: "belongs to",
  uses: "uses",
  generated_by: "generated by",
  depends_on: "depends on",
  references: "references",
  derived_from: "derived from",
};

export function isKnowledgeType(value: string): value is KnowledgeType {
  return (KNOWLEDGE_TYPES as string[]).includes(value);
}

/** Strip a "type:entity-id" namespace prefix, leaving the raw entity id. */
export function entityIdOf(namespaced: string): string {
  const i = namespaced.indexOf(":");
  return i === -1 ? namespaced : namespaced.slice(i + 1);
}